run:
  timeout: 30m

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goheader
    - gomoddirectives
    - gosec
    - grouper
    - loggercheck
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
