---
version: 2

project_name: relink

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: USA-RedDragon
    name: relink

dockers_v2:
  - images:
      - "ghcr.io/usa-reddragon/relink"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.licenses": MIT
      "org.opencontainers.image.url": "https://github.com/USA-RedDragon/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/USA-RedDragon/{{ .ProjectName }}"
    flags:
      - "--pull"

builds:
  - main: .
    binary: relink
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

milestones:
  - close: true
