// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type configShadow struct {
	LogLevel   *string `json:"log-level" toml:"log-level" yaml:"log-level"`
	Source     *string `json:"source" toml:"source" yaml:"source"`
	Target     *string `json:"target" toml:"target" yaml:"target"`
	HashJobs   *int    `json:"hash-jobs" toml:"hash-jobs" yaml:"hash-jobs"`
	BufferSize *int    `json:"buffer-size" toml:"buffer-size" yaml:"buffer-size"`
	CacheType  *string `json:"cache-type" toml:"cache-type" yaml:"cache-type"`
	CachePath  *string `json:"cache-path" toml:"cache-path" yaml:"cache-path"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.HashJobs = 4
	set("hash-jobs", configulator.LayerDefault, "default tag")
	cfg.BufferSize = 4096
	set("buffer-size", configulator.LayerDefault, "default tag")
	cfg.CacheType = CacheType("memory")
	set("cache-type", configulator.LayerDefault, "default tag")
	cfg.CachePath = ":memory:"
	set("cache-path", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Source != nil {
		cfg.Source = *s.Source
		set("source", configulator.LayerFile, file)
	}
	if s.Target != nil {
		cfg.Target = *s.Target
		set("target", configulator.LayerFile, file)
	}
	if s.HashJobs != nil {
		cfg.HashJobs = *s.HashJobs
		set("hash-jobs", configulator.LayerFile, file)
	}
	if s.BufferSize != nil {
		cfg.BufferSize = *s.BufferSize
		set("buffer-size", configulator.LayerFile, file)
	}
	if s.CacheType != nil {
		cfg.CacheType = CacheType(*s.CacheType)
		set("cache-type", configulator.LayerFile, file)
	}
	if s.CachePath != nil {
		cfg.CachePath = *s.CachePath
		set("cache-path", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "source"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Source = v
			set("source", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "target"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Target = v
			set("target", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "hash-jobs"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "hash-jobs",
					Source: n,
					Value:  v,
				}
			}
			cfg.HashJobs = int(p)
			set("hash-jobs", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "buffer-size"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "buffer-size",
					Source: n,
					Value:  v,
				}
			}
			cfg.BufferSize = int(p)
			set("buffer-size", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "cache-type"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.CacheType = CacheType(v)
			set("cache-type", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "cache-path"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.CachePath = v
			set("cache-path", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"source"}, o.Separator), strings.Join([]string{"target"}, o.Separator), strings.Join([]string{"hash-jobs"}, o.Separator), strings.Join([]string{"buffer-size"}, o.Separator), strings.Join([]string{"cache-type"}, o.Separator), strings.Join([]string{"cache-path"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(strings.Join([]string{"source"}, o.Separator), "", "Source directory to read the files from")
	fs.String(strings.Join([]string{"target"}, o.Separator), "", "Target directory to write the relinked files to")
	fs.Int(strings.Join([]string{"hash-jobs"}, o.Separator), 4, "Number of jobs to use for hashing files")
	fs.Int(strings.Join([]string{"buffer-size"}, o.Separator), 4096, "Buffer size for file checksum operations in bytes")
	fs.String(strings.Join([]string{"cache-type"}, o.Separator), "memory", "Cache type to use for storing file hashes. One of memory or sqlite")
	fs.String(strings.Join([]string{"cache-path"}, o.Separator), ":memory:", "Path to the SQLite database file for caching. Only used if cache-type is sqlite")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"source"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "source",
				Source: "--" + n,
			}
		}
		cfg.Source = v
		set("source", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"target"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "target",
				Source: "--" + n,
			}
		}
		cfg.Target = v
		set("target", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"hash-jobs"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "hash-jobs",
				Source: "--" + n,
			}
		}
		cfg.HashJobs = v
		set("hash-jobs", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"buffer-size"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "buffer-size",
				Source: "--" + n,
			}
		}
		cfg.BufferSize = v
		set("buffer-size", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"cache-type"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cache-type",
				Source: "--" + n,
			}
		}
		cfg.CacheType = CacheType(v)
		set("cache-type", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"cache-path"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cache-path",
				Source: "--" + n,
			}
		}
		cfg.CachePath = v
		set("cache-path", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "source":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Source = &str
			default:
				return fmt.Errorf("source: expected a string, got %v", v.Kind())
			}
		case "target":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Target = &str
			default:
				return fmt.Errorf("target: expected a string, got %v", v.Kind())
			}
		case "hash-jobs":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.HashJobs = &val
			default:
				return fmt.Errorf("hash-jobs: expected a number, got %v", v.Kind())
			}
		case "buffer-size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.BufferSize = &val
			default:
				return fmt.Errorf("buffer-size: expected a number, got %v", v.Kind())
			}
		case "cache-type":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.CacheType = &str
			default:
				return fmt.Errorf("cache-type: expected a string, got %v", v.Kind())
			}
		case "cache-path":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.CachePath = &str
			default:
				return fmt.Errorf("cache-path: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("source = %v\n", c.Source))
	b.WriteString(fmt.Sprintf("target = %v\n", c.Target))
	b.WriteString(fmt.Sprintf("hash-jobs = %v\n", c.HashJobs))
	b.WriteString(fmt.Sprintf("buffer-size = %v\n", c.BufferSize))
	b.WriteString(fmt.Sprintf("cache-type = %v\n", c.CacheType))
	b.WriteString(fmt.Sprintf("cache-path = %v\n", c.CachePath))
	return b.String()
}
