// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type configShadow struct {
	LogLevel   *string `json:"log-level"   toml:"log-level"   yaml:"log-level"`
	Source     *string `json:"source"      toml:"source"      yaml:"source"`
	Target     *string `json:"target"      toml:"target"      yaml:"target"`
	HashJobs   *int    `json:"hash-jobs"   toml:"hash-jobs"   yaml:"hash-jobs"`
	BufferSize *int    `json:"buffer-size" toml:"buffer-size" yaml:"buffer-size"`
	CacheType  *string `json:"cache-type"  toml:"cache-type"  yaml:"cache-type"`
	CachePath  *string `json:"cache-path"  toml:"cache-path"  yaml:"cache-path"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.HashJobs = 4
	set("hash-jobs", configulator.LayerDefault, "default tag")
	cfg.BufferSize = 4096
	set("buffer-size", configulator.LayerDefault, "default tag")
	cfg.CacheType = CacheType("memory")
	set("cache-type", configulator.LayerDefault, "default tag")
	cfg.CachePath = ":memory:"
	set("cache-path", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Source != nil {
		cfg.Source = *s.Source
		set("source", configulator.LayerFile, file)
	}
	if s.Target != nil {
		cfg.Target = *s.Target
		set("target", configulator.LayerFile, file)
	}
	if s.HashJobs != nil {
		cfg.HashJobs = *s.HashJobs
		set("hash-jobs", configulator.LayerFile, file)
	}
	if s.BufferSize != nil {
		cfg.BufferSize = *s.BufferSize
		set("buffer-size", configulator.LayerFile, file)
	}
	if s.CacheType != nil {
		cfg.CacheType = CacheType(*s.CacheType)
		set("cache-type", configulator.LayerFile, file)
	}
	if s.CachePath != nil {
		cfg.CachePath = *s.CachePath
		set("cache-path", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "source"); ok {
		cfg.Source = v
		set("source", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "target"); ok {
		cfg.Target = v
		set("target", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "hash-jobs"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "hash-jobs",
				Source: n,
				Value:  v,
			}
		}
		cfg.HashJobs = int(p)
		set("hash-jobs", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "buffer-size"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "buffer-size",
				Source: n,
				Value:  v,
			}
		}
		cfg.BufferSize = int(p)
		set("buffer-size", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "cache-type"); ok {
		cfg.CacheType = CacheType(v)
		set("cache-type", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "cache-path"); ok {
		cfg.CachePath = v
		set("cache-path", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"log-level",
		"source",
		"target",
		"hash-jobs",
		"buffer-size",
		"cache-type",
		"cache-path",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(names[1], "", "Source directory to read the files from")
	fs.String(names[2], "", "Target directory to write the relinked files to")
	fs.Var(impl.NewInt(4), names[3], "Number of jobs to use for hashing files")
	fs.Var(impl.NewInt(4096), names[4], "Buffer size for file checksum operations in bytes")
	fs.String(names[5], "memory", "Cache type to use for storing file hashes. One of memory or sqlite")
	fs.String(names[6], ":memory:", "Path to the SQLite database file for caching. Only used if cache-type is sqlite")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "source"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "source",
				Source: "--" + n,
			}
		}
		cfg.Source = v
		set("source", configulator.LayerCLI, "--"+n)
	}
	if n := "target"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "target",
				Source: "--" + n,
			}
		}
		cfg.Target = v
		set("target", configulator.LayerCLI, "--"+n)
	}
	if n := "hash-jobs"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "hash-jobs",
				Source: "--" + n,
			}
		}
		cfg.HashJobs = v
		set("hash-jobs", configulator.LayerCLI, "--"+n)
	}
	if n := "buffer-size"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "buffer-size",
				Source: "--" + n,
			}
		}
		cfg.BufferSize = v
		set("buffer-size", configulator.LayerCLI, "--"+n)
	}
	if n := "cache-type"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cache-type",
				Source: "--" + n,
			}
		}
		cfg.CacheType = CacheType(v)
		set("cache-type", configulator.LayerCLI, "--"+n)
	}
	if n := "cache-path"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cache-path",
				Source: "--" + n,
			}
		}
		cfg.CachePath = v
		set("cache-path", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "source":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Source = &str
			default:
				return configJSONError("source", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "target":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Target = &str
			default:
				return configJSONError("target", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "hash-jobs":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError("hash-jobs", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError("hash-jobs", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.HashJobs = &num
			default:
				return configJSONError("hash-jobs", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "buffer-size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError("buffer-size", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError("buffer-size", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.BufferSize = &num
			default:
				return configJSONError("buffer-size", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "cache-type":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.CacheType = &str
			default:
				return configJSONError("cache-type", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "cache-path":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.CachePath = &str
			default:
				return configJSONError("cache-path", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "source = %v\n", c.Source)
	fmt.Fprintf(&b, "target = %v\n", c.Target)
	fmt.Fprintf(&b, "hash-jobs = %v\n", c.HashJobs)
	fmt.Fprintf(&b, "buffer-size = %v\n", c.BufferSize)
	fmt.Fprintf(&b, "cache-type = %v\n", c.CacheType)
	fmt.Fprintf(&b, "cache-path = %v\n", c.CachePath)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
