name: Config Docs

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  config-docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.AUTO_COMMIT_APP_ID }}
          private-key: ${{ secrets.AUTO_COMMIT_APP_KEY }}

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: USA-RedDragon/reusable-actions/configulator-docs@70c0fd29a3fb180e92e0b4e39c90982da4b5d07e # v2.0.26
        with:
          dir: internal/config
          type: Config
          git-user-name: usa-reddragon-auto-commit-bot[bot]
          git-user-email: usa-reddragon-auto-commit-bot[bot]@users.noreply.github.com
