name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@4a4ab216b29662f3424712de85cf3a0a1a0ac7af # v2.0.19
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
