name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@70c0fd29a3fb180e92e0b4e39c90982da4b5d07e # v2.0.26
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
