name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@5482af692f1d81ac14dbe6da6984268722569d90 # v2.0.15
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
